### ISSUE TITLE
Also consider file_managed table for sources 

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/filefield_sources#14]
When selecting from existing fields, all file fields are considered (depends on setting).

However, there's no option to search in file_managed table, which is the reason why files uploaded directly (/admin/content/files, link + Add a file) aren't accessible for the autocomplete functionality.

That would be a nice addition for Backdrop. Is it worth considering?

**Comment by herbdool** [comment]
@indigoxela good idea. I've added a PR. Maybe could use some refining. Does it also capture files uploaded via ckeditor?

**Comment by indigoxela** [comment]
Great! I tested locally and it works. :tada: 

> Does it also capture files uploaded via ckeditor?

Yes, after the node where the upload happened got saved, also these files are available via autocomplete. Any managed file is.

**Comment by indigoxela** [comment]
> Any managed file is.

... Regardless of file type / extension, which might need some tweaks. Why autocomplete files that aren't valid for that field, anyway?

**Comment by herbdool** [comment]
Good catch. I think we'll need to introduce checking by mime type, which it didn't need to do before since it seems to be just checking if a file was assigned to field(s).

**Comment by herbdool** [comment]
@indigoxela it's now filtering by file extension. I tried to improve the text on the options as well.

(In order to get this merged I may have to volunteer to be the maintainer :)).

**Comment by indigoxela** [comment]
Great, this works as expected now! No more unusable results in the list.

One thought: you're doing the filtering for extension _after_ getting the range (30) from the database, which means that if lots of other filetypes are in the initial db result, you'd possibly end up with few or even none in the dropdown (after filtering happened).

The file_managed table has no "extension" column, so you can't directly query for that. And there can be lots of allowed extensions, so using "OR" might not be the best solution performance-wise. Maybe "REGEXP"? Not sure.

Does anything smart come to your mind @herbdool?

**Comment by herbdool** [comment]
@indigoxela thanks for catching that. I didn't notice the limit. I agree about using mysql REGEXP so I've updated the PR. Should be more efficient this way too.

**Comment by indigoxela** [comment]
Great, works like a charm!
