### ISSUE TITLE
Duplicated files?

### ISSUE THREAD

**Issue by diannevolek** [backdrop-contrib/filefield_sources#15]
I have several modules working together, but I think the issue is coming from filefield_sources. It could also be my setup which I described below.

I keep all downloads under a single folder called Files/Downloads. I FTP a few hundred  files there, and I then attach the same files to many different content pages (many of the products use the same installation diagrams). 

When I select an existing file, it appears to duplicate the file, but rewriting some characters. (changing everything to lower case, and replacing underlines/spaces with hyphens). These don't appear as temporary files I can delete through the admin area, but they are in the folder on the server. I will test to see if they duplicate every time I attach the same file, or just the first time. 

I set the config to "leave the file in the folder" because I always want the master file to be available. Perhaps I should turn this off? I need the uppercase characters and underlines to remain in the file name. I'll check if the Drupal forums have additional help on the config parameters so it can be included in our help files.

**Comment by diannevolek** [comment]
There is a Drupal forum comment

On my files uploaded with filefield_sources - "File attach from server directory" are renamed. Character + is removed.
It seems it is because of filefield_sources_clean_filename() which is using transliteration_clean_filename().
IMHO it should respect transliteration settings "Transliterate file names during upload." on this page admin/config/media/file-system

It might not be worth changing, but perhaps warn people? I think for most people it wouldn't matter.

**Comment by herbdool** [comment]
Actually `filefield_sources_clean_filename()` is first checking if the *module* `transliteration` exists before trying to translate. Now this functionality is in core, but it's not a module so this shouldn't be running.

There is a contrib module https://github.com/backdrop-contrib/transliteration/releases/tag/1.x-1.0.4 but someone shouldn't be able to install it - it's been blocked.

So this module shouldn't be checking for transliteration module but I don't see how it's causing the issue you see.

**Comment by diannevolek** [comment]
I am not sure where the transliteration is happening, and perhaps a different setup will stop it. I've tried to track it, but I changed the process more than once, first uploading later uploading with the browse button, and later FTPing the files and then using "FileAttach". I worked through the files it in order so D_P3 files were definitely using file attach.

These are the original files - only uppercase.

![original files](https://user-images.githubusercontent.com/86380416/147359649-be9eef9f-e8af-4aa2-be55-0fe273a77ad3.jpg)

**Comment by diannevolek** [comment]
The CPanel File manager with both files and lower case duplicates and _0 rename.

![cPanel File Manager v3 - 2021_697 - ](https://user-images.githubusercontent.com/86380416/147360335-681c4df2-ae1c-4d1e-8f0d-275f934a640d.jpg)

**Comment by diannevolek** [comment]
There are NO lowercase files in the file manager under D-P3. Even though some are used under file attach. They appear in the select list, but they aren't under manage files.

The manage files is a great idea, and therefore File Field Sources is probably not an ideal module for users who don't understand the consequences. They might blame backdrop when files aren't replaced, but the files they are replacing are the ones being used on the website!

After think about this a lot, if you could add a "select existing" to files, it could circumvent the whole File Field Sources confusion?


![Content - CBI Inc - 2021_698 - ](https://user-images.githubusercontent.com/86380416/147360462-1fbce3dd-d56a-465f-b243-e41613febdad.jpg)

**Comment by diannevolek** [comment]
Image Cpanel: In the downloads folder on the server, I have both capitalised files AND lowercase files. Not the d_p3 that has _0 added to the file name. This is a file that is now in 3 places.

![cPanel File Manager v3 - 2021_697 - ](https://user-images.githubusercontent.com/86380416/147361133-09db0730-66fe-422b-899a-9ea8838fab25.jpg)

**Comment by diannevolek** [comment]
Image: File Attach. When I try to attach files only the lower case versions are offered of the D_P3_
![file attach options](https://user-images.githubusercontent.com/86380416/147361153-e868db3b-6d20-47a0-aa23-725ce4555976.jpg)


This is the page where I originally uploaded the files - you'll see under DD Frame, all the download PDFs are upper case.

https://www.cbi-lowvoltage.com/vocabulary/frame 

On this page where I started attaching files (using File Attach) to the Handles page (same files) the Rocker Handles are now lower case files. No Upper case files are available in the D_P3 range to select, only lower case versions. But the Toggles remain upper case. I have no idea why they are different. 

https://www.cbi-lowvoltage.com/vocabulary/actuator_handle

**Comment by herbdool** [comment]
I can't really follow your comments @diannevolek. If you would like to help see if the bug is with this module I recommend you test the latest unreleased version of this module on a fresh install of Backdrop with no other contrib modules. That's the only way to find the source.

I had tested it on a fresh install and could not replicate your second comment. When I turn off transliteration in Backdrop it doesn't rename the files here

**Comment by diannevolek** [comment]
Sorry, you're quite right, my transliteration was still on!
