### ISSUE TITLE
Error: You do not have permission to use the selected file.

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/filefield_sources#6]
I added this to a site and tried to reference a file that was used in one content type from an image field in another content type. I get:

> You do not have permission to use the selected file.

Shouldn't I be able to use a file across content types?

**Comment by laryn** [comment]
Update: this seems to be happening within content type fields as well.

Catching up on commits with the Drupal module may help, or be a good place to start.

**Comment by quicksketch** [comment]
I think this may have been resolved in https://www.drupal.org/node/2176133. I'll be doing a merge to pull in FileField Sources 1.11 updates and we should get that fix included in the ports.

**Comment by quicksketch** [comment]
This should be fixed as part of https://github.com/backdrop-contrib/filefield_sources/issues/7.
